#!/bin/bash
set -x

if [ ! -e $HOME/bin ]; then
    mkdir $HOME/bin
fi

# $HOME/bin insertion in the PATH variable, if it does not exist
read dirs << EOF
$PATH
EOF

IFS=:

contains_bin=0
for dir in $dirs; do
    if [ "$dir" = "$HOME/bin" ]; then
        contains_bin=1
    fi
done

IFS=

if [ $contains_bin = 0 ]; then
    PATH=$HOME/bin:$PATH
fi
# End of $HOME/bin insertion in the PATH variable

make -C src all
set +x
